---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
    server {

      listen         80;
      server_name    _default_;
      root           /usr/share/nginx/html/;
      index          index.php;
      location / {
        try_files $uri $uri/ /index.php?$args;
      }


      location ~ \.php$ {
        root /var/www/html/;
        fastcgi_pass php-service-cluster-ip:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
      }

    }
